
[model]
name = "LAMMPS"
targets = ["atm", "atm-2"]
model_files = ["LAMMPS/in.atm"]
experiment = "lammps_atm"

[control]
executable = "lmp_mpi"
run_command = "mpirun"
run_args = "-np 6"
exe_args = "-in in.atm"


[atm]
    [atm.25]
    value = [20, 25]

[atm-2]
    [atm-2.25]
    value = [30, 35]

    





