
[model]
name = "LAMMPS"
targets = ["atm", "atm-2"]
model_files = ["./in.atm"]
experiment = "lammps_atm"

[control]
executable = "lmp_mpi"
run_command = "mpirun"
run_args = "-np 6"
exe_args = "-in in.atm"
launcher = "local"


[atm]
    [atm.STEPS]
    value = [20, 25]
    [atm.THERMO]
    value = [10, 20]

[atm-2]
    [atm-2.STEPS]
    value = [30, 35]
    [atm-2.THERMO]
    value = [30, 40]





