
[parameters]
# each parameter listed should contain each value that could be a result
# of tuning the model. Permutations of all listed parameters will be run.
    KH = [1000, 2000, 3000, 4000]
    KHTH = [1000, 2000, 3000, 4000]

[parameter_info]
    filename = "MOM_override"
    filetype = "txt"

[low]
    [low.NIGLOBAL]
        value = 20
        filename = "MOM_override"
        filetype = "txt"
    [low.NJGLOBAL]
        value = 20
        filename = "MOM_override"
        filetype = "txt"
    [low.nk]
        value = 1
        filename = "MOM_override"
        filetype = "txt"
    [low.months]
        value = 12
        filename = "input.nml"
        filetype = "nml"


[high]
    [high.NIGLOBAL]                # resolution
        value = 40
        filename = "MOM_override"
        filetype = "txt"
    [high.NJGLOBAL]                # resolution
        value = 40
        filename = "MOM_override"
        filetype = "txt"
    [high.nk]                      # layers
        value = 1
        filename = "MOM_override"
        filetype = "txt"
    [high.months]                  # simulation length
        value = 12
        filename = "input.nml"
        filetype = "nml"


[MPO_settings]
# MPO should assume defaults for these values
# but should also be customizable by the user
procs_per_node = 48
executable_path = "../../../Ocean/MOM6-examples/build/gnu/ocean_only/repro/MOM6"
base_config_path = "../MOM6_base_config"
low_nodes = 2
high_nodes = 4
