
[model]
name = "CP2K"
model_files = ["CP2K/h2o.inp"]
experiment = "h2o"
targets = ["h2o-1"]

[control]
executable = "cp2k.psmp"
run_command = "srun"
launcher = "slurm"
         [control.h2o-1]
         nodes = 1
         partition = "gpu"
         exe_args = "-i h2o.inp"

[h2o-1]
    [h2o-1.2]  # editing number of steps
    value = [5, 10, 15, 20]