

[model]
name = "MOM6"

[execute]
targets = ["half-deg", "quar-deg"]
executable_path = "../../../Ocean/MOM6-examples/build/gnu/ocean_only/repro/MOM6"


[machine]
partition = "iv24"
launcher = "slurm"
nodes = 1          # can set nodes from here
ppn = 1            # like this

# or

  [machine.half-deg]
  partition = "iv24"
  launcher = "slurm"
  nodes = 4

  [machine.quar-deg]
  parition = "iv24"
  launcher = "slurm"
  nodes = 4
