
[model]
name = "MOM6"
configs = ["MOM6_base_config"]
experiment = "double_gyre"

[execute]
targets = ["half-deg", "quar-deg", "one-deg"]
executable = "MOM6"
run_command = "srun"
launcher = "slurm"
         [execute.quar-deg]
         nodes = 3
         [execute.half-deg]
         nodes = 2
         [execute.one-deg]
         nodes = 1

[quar-deg]
    [quar-deg.999]
        value = [200, 400, 700, 800, 1000]
    [quar-deg.0]
        value = [200, 400, 700, 800, 1000]
    [quar-deg.80]
        value = 80
    [quar-deg.40]
        value = 40


[half-deg]
    [half-deg.999]
        value = [200, 400, 700, 800, 1000]
    [half-deg.0]
        value = [200, 400, 700, 800, 1000]
    [half-deg.80]
        value = 40
    [half-deg.40]
        value = 20

[one-deg]
    [one-deg.999]
        value = [200, 400, 700, 800, 1000]
    [one-deg.0]
        value = [200, 400, 700, 800, 1000]
    [one-deg.80]
        value = 20
    [one-deg.40]
        value = 20