
[model]
name = "MOM6"
model_files= ["MOM6/MOM6_base_config"]
experiment = "double_gyre"
targets = ["half-deg", "quar-deg"]

[control]
executable = "MOM6"
run_command = "srun"
partition = "iv24"
launcher = "slurm"
         [control.quar-deg]
         nodes = 2
         [control.half-deg]
         nodes = 1
         
[quar-deg]  
    [quar-deg.KH]
        value = [200, 400, 700]
    [quar-deg.KHTH]
        value = [200, 400, 700]
    [quar-deg.x_resolution]
        value = 80
    [quar-deg.y_resolution]
        value = 40
    [quar-deg.months]
        value = 1


[half-deg]
    [half-deg.KH]
        value = [200, 400, 700]
    [half-deg.KHTH]
        value = [200, 400, 700]
    [half-deg.x_resolution]
        value = 40
    [half-deg.y_resolution]
        value = 20
    [half-deg.months]
        value = 1

