
[model]
name = "MOM6"
configs = ["MOM6_base_config"]
experiment_name = "double_gyre"

[execute]
targets = ["quar-deg"]
executable_path = "../../../Ocean/MOM6-examples/build/gnu/ocean_only/repro/MOM6"
run_command = "srun"
launcher = "slurm"


[quar-deg]
    [quar-deg.999]
        value = [1000, 2000, 3000, 4000]
    [quar-deg.0]
        value = [1000, 2000, 3000, 4000]
    [quar-deg.80]
        value = 80
    [quar-deg.40]
        value = 40
    


