
[model]
name = "MOM6"
model_files= ["MOM6/MOM6_base_config"]
experiment = "double_gyre"
targets = ["half-deg", "quar-deg"]

[control]
executable = "MOM6"
run_command = "srun"
partition = "iv24"
launcher = "slurm"
         [control.quar-deg]
         nodes = 2
         [control.half-deg]
         nodes = 1
         
[quar-deg]
    [quar-deg.999]
        value = [200, 400, 700]
    [quar-deg.0]
        value = [200, 400, 700]
    [quar-deg.80]
        value = 80
    [quar-deg.40]
        value = 40


[half-deg]
    [half-deg.999]
        value = [200, 400, 700]
    [half-deg.0]
        value = [200, 400, 700]
    [half-deg.80]
        value = 40
    [half-deg.40]
        value = 20

