
[parameters]
# each parameter listed should contain each value that could be a result
# of tuning the model. Permutations of all listed parameters will be run.
    KH = [1000, 2000, 3000, 4000, 5000, 6000]
    KHTH = [1000, 2000, 3000, 4000, 5000, 6000]

[parameter_info]
    filename = "MOM_override"
    filetype = "txt"

[low]
    [low.NIGLOBAL]
        value = 40
        filename = "MOM_override"
        filetype = "txt"
    [low.NJGLOBAL]
        value = 40
        filename = "MOM_override"
        filetype = "txt"
    [low.months]
        value = 12
        filename = "input.nml"
        filetype = "nml"


[high]
    [high.NIGLOBAL]
        value = 40
        filename = "MOM_override"
        filetype = "txt"
    [high.NJGLOBAL]
        value = 40
        filename = "MOM_override"
        filetype = "txt"
    [high.months]
        value = 12
        filename = "input.nml"
        filetype = "nml"


[MPO_settings]
# MPO should assume defaults for these values
# but should also be customizable by the user
launcher = "slurm"
procs_per_node = 48
executable_path = "./model"
base_config_path = "../MOM6_base_config"

