name: build_wheels_cpu

on: [push, pull_request]

env:
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"
  CIBW_SKIP: "pp* *i686*" # skip building for PyPy
  CIBW_ARCHES: x86_64
  CIBW_ENVIRONMENT_MACOS: PATH="$(brew --prefix)/opt/make/libexec/gnubin:$PATH"
  MACOSX_DEPLOYMENT_TARGET: "10.09"


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        gcc_v: [8]
    env:
      GCC_V: ${{ matrix.gcc_v }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Install build-essentials
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y wget

      - name: Install GNU make for MacOS
        if: contains(matrix.os, 'macos')
        run: brew install make || true

      - name: Install GCC macOS
        if: contains(matrix.os, 'macos')
        run: brew install gcc@${GCC_V} || brew upgrade gcc@${GCC_V} || true

      - name: list target wheels
        run: |
          python -m cibuildwheel . --print-build-identifiers

      - name: Make Dependencies
        run: |
          /bin/bash build-scripts/make-deps.sh

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT_MACOS: PATH="$(brew --prefix)/opt/make/libexec/gnubin:$PATH"
          MACOSX_DEPLOYMENT_TARGET: "10.09"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
